### ISSUE TITLE
Remove references to Sage installation guide

### ISSUE THREAD

**Issue by kcrisman** [dandrake/sagetex#17]
This is not correct any more:
> See the Sage installation guide at http://doc.sagemath.org/html/en/installation/ 

So we need to update this: see downstream at https://trac.sagemath.org/ticket/22499

It does seem that the pdfs are still installed though, which is good.

**Comment by kcrisman** [comment]
See also https://trac.sagemath.org/ticket/21450

**Comment by kcrisman** [comment]
@dimpase This is still incorrect; the installation guide has no references to SageTeX any more, I think.

**Comment by dimpase** [comment]
Do you mean the installation guide of SageTeX? Or of Sage? There are two separate things here: installation of SageTeX python component, and making TeX aware of SageTeX.
Which one do you mean?

**Comment by kcrisman** [comment]
I mean the installation guide of Sage has no references to SageTeX, to my knowledge.

```
tutorial $ grep -i sagetex *.rst | wc 
      66     595    4658
tutorial $ cd ../installation/
installation $ grep -i sagetex *.rst | wc 
       0       0       0
```

So the README for SageTeX in this repo that we are commenting on should change that.

More details: of the 4 files changed in #5 two are in fine shape now.  The README change I think I can try to make a manual PR for right now; the `sagetex.dtx` one I would worry about making a syntax error if I did it by hand. I'll do at least the first immediately.

**Comment by dimpase** [comment]
That's correct. I must say I'm not happy with the status of docs of sagetex - if sagetex is upstream w.r.t. sage, it should get its docs built separately, and installed into the same place as e.g. sagenb.

**Comment by kcrisman** [comment]
Hmm, I'm not sure how to fix that.  I guess that in principle there are two options:

- Have them auto-built on this site somehow and then include them in the `spkg-install`, putting them in the "right" place (which may mean updating some Sage doc nontrivially, but whatever)
- Have Sage actually build these documents while building sagetex.  That has the problem of making tex a build-time dependency which I don't think we want.

Anyway, that would be a separate issue; to be picky, it would be a Sage issue which Sage asks SageTeX to take care of ... it all seems a bit silly to me, though.

**Comment by dimpase** [comment]
TeX ought to be a dependency of SageTeX.
Not sure how to handle this, in particular as not only LaTeX is needed, but
also certain LaTeX packages.

Inability to build SageTeX docs is a good test for usefulness of SageTeX
installation, so it is good to have it built from source...

On 8 Jan 2019 3:31 pm, "kcrisman" <notifications@github.com> wrote:

Hmm, I'm not sure how to fix that. I guess that in principle there are two
options:

   - Have them auto-built on this site somehow and then include them in the
   spkg-install, putting them in the "right" place (which may mean updating
   some Sage doc nontrivially, but whatever)
   - Have Sage actually build these documents while building sagetex. That
   has the problem of making tex a build-time dependency which I don't think
   we want.

Anyway, that would be a separate issue; to be picky, it would be a Sage
issue which Sage asks SageTeX to take care of ... it all seems a bit silly
to me, though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sagemath/sagetex/issues/17#issuecomment-452340198>, or mute
the thread

**Comment by kcrisman** [comment]
Both PRs were merged so I'm closing this.  I'll open a new one for this other discussion.
